### ISSUE TITLE
Thanks For Your Project

### ISSUE THREAD

**Issue by Argosth** [mgp25/psn-api#10]
Hi dear developer, I just want to know how to include this project in my PHP website, I have Python available, but I don't know how to implement this API in my website, or how to install it.

Thank you for your attention and have a nice day.

**Comment by mgp25** [comment]
Hello @Argosth 

You can call the python script from php and then parse the response there. Right now, you only have to download the files and follow the guide that is written in the readme. Once you have your account tokens, you can re-use them anytime you want and try with the php scripts.

Regards
