### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Tomasz-Silpion** [mgp25/psn-api#15]
Worked properly for a month with a cronjob for me, then:

`urllib.error.HTTPError: HTTP Error 400: Bad Request`

error appeared yesterday. Somebody can confirm this or maybe my account was banned?

**Comment by pcmantinker** [comment]
A bad request means that the request is not what the API expects, not that you are unauthorized. You would be getting a "401 Unauthorized" response code if you were not properly authenticated/authorized. It's possible that Sony changed the request structure and this service isn't passing a correctly formed request anymore. Do you know which endpoint this happening on?

**Comment by Paxios** [comment]
> Worked properly for a month with a cronjob for me, then:
> 
> `urllib.error.HTTPError: HTTP Error 400: Bad Request`
> 
> error appeared yesterday. Somebody can confirm this or maybe my account was banned?

Hello did you manage to solve the issue?

**Comment by Tomasz-Silpion** [comment]
Yes, yesterday I've finally got some time to get back to this and figured out that I've had to renew my tokens with obtain_tokens.py script.

I can confirm that the library still works properly and I'm able to track and log my friends activity again.

```
with open(cwd + "/activity.log", "a") as log:
    log.write(now.strftime("%Y-%m-%d %H:%M") + "," + friend_string.encode('ascii', 'ignore').decode('ascii') + "\n")
```
