### ISSUE TITLE
captcha token missing

### ISSUE THREAD

**Issue by BlakeSchmidt** [mgp25/psn-api#2]
This week I get the following response back from `GrabNPSSO`:

`u'error_code': 4097, u'error_description': u'Invalid token', u'parameters': [u'captchatokenmissing'], u'docs': u'https://auth.api.sonyentertainmentnetwork.com/docs/', u'error': u'invalid_token'`

Has been working correctly for the last 6 months.

**Comment by mgp25** [comment]
Hello @BlakeSchmidt,

have you tried login in in PlayStation Network website, and once logged, using this script again?

Regards

**Comment by mgp25** [comment]
@BlakeSchmidt what you can do is, logging in via PSN website, extract the authentication bearer from the request, and use it in your script without calling `Auth()`:

```python
#auth = Auth(user, pw)
#tokens = auth.get_tokens()

tokens = {
    "oauth": 'HERE BEARER AUTH',
    "refresh": 'HERE BEARER AUTH', # this is not required tho
    "npsso": None
}
```

Regards

**Comment by trubesv** [comment]
@BlazeBoss17 @mgp25 the bearer resides in the Location response header of the last  GET https://ca.account.sony.com/api/v1/oauth/authorize request, see `access_token` parameter:
```
Location: https://social.playstation.com/starblaster2/pdc/master/auth/response-XXX.html?requestID=iframe_request_XXX&baseUrl=/starblaster2/pdc/master/&targetOrigin=https://www.playstation.com#access_token=BEARER&token_type=bearer&expires_in=XXX&cid=XXX
```
Also in the Cookie request header of the same request you can find the npsso:
```
Cookie: npsso=XXX
```
