### ISSUE TITLE
Not getting ticket_uuid parameter in url

### ISSUE THREAD

**Issue by Neppelenbroek** [mgp25/psn-api#6]
We have tried with multiple psn accounts (new & existing ones). We are not able to replicate the flow of actions that should get us a ticket_uuid parameter in the url. Can you verify this method is still working?

**Comment by mgp25** [comment]
Can you use the normal login method from PlayStation network?

Regards

**Comment by a7ypically** [comment]
Other projects are using the following link to get ticket_uuid:

https://www.bungie.net/en/User/SignIn/Psnid?code=000000

**Comment by bladefist** [comment]
@Neppelenbroek Did you ever figure out a solution? I'm seeing the same issue.  I did MITM too, that token isn't appearing.  

The verification code step no longer exists as well. @mgp25  do you know of anything I can try?

**Comment by Neppelenbroek** [comment]
I used the normal login method with no luck. Still not able yo use this repo unfortunately

**Comment by mgp25** [comment]
I am going to update the readme so anyone can use the this API.

Regards
