### ISSUE TITLE
Bug in GrabNPSSO() ?

### ISSUE THREAD

**Issue by a7ypically** [mgp25/psn-api#7]
Hi,

I could not get the npsso value as the function GrabNPSSO seems to have an indent bug. The first case where two factor auth is used never fills self.npsso.

I had to indent back the whole block of code starting from:
if hasattr(data, 'error'):

to get it working.

After that all works well, so thanks!

**Comment by mgp25** [comment]
Hello @a7ypically,

Fixed in the latest commit: https://github.com/mgp25/psn-api/commit/8bb42b1c8677300730a9596685201248f24a23ca

Regards
